### ISSUE TITLE
Create Branch Feature/HTML

### ISSUE THREAD

**Issue by Jimmykotter** [Jimmykotter/MooLah#2]

**Comment by OutsideofemiT** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Budget Tracker</title>
	<link rel="stylesheet" href=./assets/css/style.css>
</head>


<body>
    <h1 class="header">MooLah Budget Tracker</h1>;
	<img class="logo" src="./assets/images/cow_logo.jpg" alt="MooLah Logo" width="200" height="200">

</body>
</html>

**Comment by OutsideofemiT** [comment]
Updated HTML to follow wireframe.

**Comment by OutsideofemiT** [comment]
Updated HTML. Added Photos.
